name: tfbs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - pandas
  - omegaconf
  - einops
  - scikit-learn
  - bedtools
  - cyushuffle
  - ushuffle
  - meme=5.5.8
  - ghostscript
