dataset_path: [ "../data/samples/Sun2022-AtABF2_dinuc_shuffle_neg_fixed_201.csv",
                "../data/samples/Malley2016-AtABF2_dinuc_shuffle_neg_fixed_201.csv" ]

############
name: "AtABF2_cross-dataset-dinuc_shuffle"
split_dir: "../data_splits/"
test_split_type: "cross"  # Options: 'random' or 'cross'
val_split_type: "n-fold" # Options: 'cross', 'n-fold' - can be 'cross' when test_split_type is 'cross', as well
id_column: "dataset"
val_ids: [] # should be assigned for 'val_split_type'='cross'
test_ids: ["Sun2022"] # should be assigned for 'test_split_type'='cross'
test_size: 0.2 # should be assigned for 'test_split_type'='random'
hold_out_val_size: 0.05
fold: 5 # should be > 1 for 'val_split_type'='n-fold'
random_state: 436346
partition_mode: 'relaxed' # Options: 'relaxed' or 'strict'
sim: 0.9 # required when 'partition_mode' is strict
word_size: 8 # required when 'partition_mode' is strict