output_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/TFBS/TFBS/MLCB_outputs"

model:
  model_name: "motif-based"
nmotifs: 5
qval_thresholds: [0.05] #  , 1e-2, 1e-3, 1e-4, 1e-5]
seeds: [565764, 535646, 224359, 989746, 654678]

