dataset_path: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/inputs/AtABFs_training_shuffle_neg_stride_200.csv"
output_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/outputs"

name: "AtABFs_cross_chromosome_2"
  
dataset_split:
  dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/inputs/data_splits"
  test_split_type: "cross"  # Options: 'random' or 'cross'
  val_split_type: "n-fold" # Options: 'cross', 'n-fold' - can be 'cross' when test_split_type is 'cross', as well
  id_column: "chromosomeId"
  val_ids: [] # should be assigned for 'cross' val_split_type
  test_ids: [2] # should be assigned for 'cross' test_split_type
  test_size: 0.2 # should be assigned for 'random' test_split_type
  fold: 5 # should be > 1 for 'n-fold' val_split_type, else 1
  random_state: 436346
  partition_mode: 'relaxed' # Options: 'relaxed' or 'strict'
  sim: 0.9 # required when 'partition_mode' is strict
  word_size: 8 # required when 'partition_mode' is strict

model:
  model_name: "HyenaDNA"
  model_version: "hyenadna-tiny-1k-seqlen"
  use_padding: true
  max_length: 264
  use_saved_model: false
  saved_model_name: ""
  finetune_type: "standard" # options: LoRA, standard

device: "cuda"
  
training:
  num_epochs: 60
  adjustable_LR:
    enabled: false
  model_params:
    train_batch_size: [32]
    learning_rate: [1e-4]
    weight_decay: [0.1]
    freeze_layers: [ [ 'backbone' ], [ 'backbone.embeddings' ], [ 'backbone.layers' ], [ 'none' ] ]
    # 'backbone.embeddings': Freezes the embedding layer.
    # 'backbone.layers'    : Freezes all transformer blocks.
    # 'backbone.layers.[i]': Freezes a specific transformer block.
    # 'backbone'           : Freezes the entire backbone (embeddings + all transformer layers).
    # 'head'               : Freezes the output classification head.

#    batch_size: [ 32, 64, 128, 256 ]
#    learning_rate: [ 1e-6, 1e-5, 1e-4, 1e-3 ]
#    weight_decay: [ 0.0, 0.01, 0.1 ]
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: 'dc3d431c0afb735d9ac046c72f076bf1f7656472'
  entity_name: 'haghani-vt'
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'