output_dir: "../outputs"

model:
  model_name: "AgroNT"
  use_padding: true
  max_length: 264
  finetune_type: "standard" # options: LoRA, standard

device: "cuda"
eval_batch_size: 64

training:
  num_epochs: 60
  adjustable_LR:
    enabled: false
  model_params:
    freeze_layers: ['none']
    train_batch_size: [8]
    learning_rate: [1e-5]
    weight_decay: [0.1]
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: 'dc3d431c0afb735d9ac046c72f076bf1f7656472'
  entity_name: 'haghani-vt'
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'