output_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/outputs"

model:
  model_name: "AgroNT"
  use_padding: true
  max_length: 264
  finetune_type: "standard" # options: LoRA, standard

split_config: # SAME AS CONFIG IN "data_split" DIR
  name: "AtABFs_random"
  split_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/data_splits"
  test_split_type: "random"  # Options: 'random' or 'cross'
  val_split_type: "n-fold" # Options: 'cross', 'n-fold' - can be 'cross' when test_split_type is 'cross', as well
  id_column: ""
  val_ids: [ ] # should be assigned for 'cross' val_split_type
  test_ids: [ ] # should be assigned for 'cross' test_split_type
  test_size: 0.2 # should be assigned for 'random' test_split_type
  fold: 5 # should be > 1 for 'n-fold' val_split_type, else 1
  partition_mode: 'strict' # Options: 'relaxed' or 'strict'
  sim: 0.9 # required when 'partition_mode' is strict
  word_size: 8 # required when 'partition_mode' is strict

device: "cuda"
eval_batch_size: 64

training:
  num_epochs: 60
  adjustable_LR:
    enabled: false
  model_params:
    train_batch_size: [8]
    learning_rate: [1e-5]
    weight_decay: [0.1]
    freeze_layers: ['none']
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: 'dc3d431c0afb735d9ac046c72f076bf1f7656472'
  entity_name: 'haghani-vt'
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'