output_dir: "../outputs"

model:
  model_name: "AgroNT"
  use_padding: true
  max_length:  265
  finetune_type: "standard" # options: LoRA, standard
  seeds: [565764, 535646, 224359, 989746, 654678]

device: "cuda"
eval_batch_size: 64

training:
  num_epochs: 60
  adjustable_LR:
    enabled: false
  freeze_layers: 'none'
  model_params:
    train_batch_size: [8]
    learning_rate: [1e-5]
    weight_decay: [0.1]
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: ''
  entity_name: ''
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'