output_dir: "../outputs"

model:
  model_name: "DNABERT-2"
  max_length: 265
  finetune_type: "standard" # options: LoRA, standard
  seeds: [565764, 535646, 224359, 989746, 654678]

device: "cuda"

training:
  num_epochs: 15
  adjustable_LR:
    enabled: true
    max: 2e-6
    min: 1.5e-5
  freeze_layers: 'none'
  model_params:
    train_batch_size: [32]
    learning_rate: [1.5e-5]
    weight_decay: [1e-2]
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: ''
  entity_name: ''
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'