output_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/outputs"

model:
  model_name: "DNABERT-2"
  max_length: 264
  finetune_type: "standard" # options: LoRA, standard

split_config: # SAME AS CONFIG IN "data_split" DIR
  name: "AtABF2_cross-dataset"
  split_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/data_splits"
  test_split_type: "cross"  # Options: 'random' or 'cross'
  val_split_type: "n-fold" # Options: 'cross', 'n-fold' - can be 'cross' when test_split_type is 'cross', as well
  id_column: "dataset"
  val_ids: [ ] # should be assigned for 'val_split_type'='cross'
  test_ids: ["Josey"] # should be assigned for 'test_split_type'='cross'
  test_size: 0.2 # should be assigned for 'test_split_type'='random'
  fold: 5 # should be > 1 for 'val_split_type'='n-fold'
  partition_mode: 'relaxed' # Options: 'relaxed' or 'strict'
  sim: 0.9 # required when 'partition_mode' is strict
  word_size: 8 # required when 'partition_mode' is strict

device: "cuda"

training:
  num_epochs: 15
  adjustable_LR:
    enabled: true
    max: 2e-6
    min: 1.5e-5
  model_params:
    freeze_layers: ['none']
    train_batch_size: [32]
    learning_rate: [1.5e-5]
    weight_decay: [1e-2]
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: 'dc3d431c0afb735d9ac046c72f076bf1f7656472'
  entity_name: 'haghani-vt'
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'