output_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/outputs"

model:
  model_name: "HyenaDNA"
  model_version: "hyenadna-tiny-1k-seqlen"
  use_padding: true
  max_length: 264
  finetune_type: "standard" # options: LoRA, standard

device: "cuda"

training:
  num_epochs: 60
  adjustable_LR:
    enabled: false
  model_params:
    freeze_layers: ['none']
    # freeze_layers: [ [ 'backbone' ], [ 'backbone.embeddings' ], [ 'backbone.layers' ], [ 'none' ] ]
    train_batch_size: [32]
    #    train_batch_size: [ 32, 64, 128, 256 ]
    learning_rate: [1e-4]
    #    learning_rate: [ 1e-6, 1e-5, 1e-4, 1e-3 ]
    weight_decay: [0.1]
    #    weight_decay: [ 0.0, 0.01, 0.1 ]
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: 'dc3d431c0afb735d9ac046c72f076bf1f7656472'
  entity_name: 'haghani-vt'
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'