output_dir: "../outputs"

model:
  model_name: "HyenaDNA"
  model_version: "hyenadna-tiny-1k-seqlen"
  use_padding: true
  max_length: 265
  finetune_type: "standard" # options: LoRA, standard
  seeds: [565764, 535646, 224359, 989746, 654678]

device: "cuda"

training:
  num_epochs: 60
  adjustable_LR:
    enabled: false
  #    freeze_layers: 'none'
  freeze_layers: ['backbone.layers', 'backbone', 'backbone.embeddings', 'none']
  model_params:
    train_batch_size: [32]
    #    train_batch_size: [ 32, 64, 128, 256 ]
    learning_rate: [1e-4]
    #    learning_rate: [ 1e-6, 1e-5, 1e-4, 1e-3 ]
    weight_decay: [0.1]
    #    weight_decay: [ 0.0, 0.01, 0.1 ]
  early_stopping:
    patience: 10
    delta: 0.0

wandb:
  enabled: True
  token: ''
  entity_name: ''
  timezone: 'US/Eastern'
  timezone_format: '%Y-%m-%d_%H-%M-%S'