input_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/TFBS/TFBS/inputs/samples/Sun2022-SiABFs_shuffle_neg_stride_200.csv"

model:
  model_name: "DNABERT-2"
  max_length: 264
  saved_model_dir: "../outputs/ABFs_cross-species/test-Si/DNABERT-2/standard/relaxed/models"

device: "cuda"
eval_batch_size: 32