input_dir: "../data/samples/Sun2022-SiABFs_dinuc_shuffle_neg_stride_200.csv" # At-Si

model:
  model_name: "DNABERT-2"
  max_length: 265
  saved_model_dir: "../outputs/AtABF2_cross-dataset-dinuc_shuffle/test-Sun2022/DNABERT-2/standard/relaxed/models" #cross-dataset

device: "cuda"
eval_batch_size: 32
num_saliency_samples: 0