device: "cuda"
eval_batch_size: 64

model:
  model_name: "AgroNT"
  use_padding: true
  max_length: 264
  finetune_type: "standard" # options: LoRA, standard
  pooling_method: "first_token"
  use_pretrained_model: true

# required when use_pretrained_model is false (use_saved_model)
output_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/HyenaDNA/TFBS/outputs"

