# set 'dataset_dir' for getting embedding of original models (use_saved_model: false)
# otherwise must pass split_config
#dataset_dir: "../data_splits/ABFs_cross-species/test-['At']-relaxed"


model:
  model_name: "DNABERT-2"
  max_length: 264
  finetune_type: "standard"
  pooling_method: "mean" # options: first_token, last_token, mean
  use_saved_model: false
  saved_model_name: ""

output_dir: "../outputs"
device: "cuda"
eval_batch_size: 32