device: "cuda"
eval_batch_size: 32

model:
  model_name: "DNABERT-2"
  max_length: 264
  finetune_type: "standard"
  pooling_method: "mean"
  use_pretrained_model: true

# required when use_pretrained_model is false (use_saved_model)
output_dir: "/projects/intro2gds/Maryam_HyenaDNA_202503/TFBS/TFBS/outputs"